### ISSUE TITLE
2 validation errors for OneMessage

### ISSUE THREAD

**Issue by Pozaza** [prtolem/MailTM#12]
File "c:\Users\Pozaza\Desktop\SD3\sd3\main.py", line 98, in get_link
    link = await mailtm.get_message_by_id(messages.hydra_member[0].id, account.token.token)
  File "c:\Users\Pozaza\Desktop\SD3\sd3\venv\lib\site-packages\mailtmapi\mailtm.py", line 140, in get_message_by_id
    return OneMessage(**(await response.json()))
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for OneMessage
verifications
  value is not a valid list (type=type_error.list)
attachments
  field required (type=value_error.missing)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000000349B8E0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000000002AEFADA0>, 22518.421)]']
connector: <aiohttp.connector.TCPConnector object at 0x000000002B7B39D0>

code:
```python
async def get_link(mailtm: MailTM, account: Account):
    messages = await mailtm.get_messages(account.token.token, 1)

    for _ in range(10):
        if len(messages.hydra_member) > 0:
            break
        await asyncio.sleep(2)
        messages = await mailtm.get_messages(account.token.token, 1)

    link = await mailtm.get_message_by_id(messages.hydra_member[0].id, account.token.token)
```

**Comment by Pozaza** [comment]
maybe you need to update pip library

**Comment by prtolem** [comment]
install it from 
`pip install https://github.com/prtolem/MailTM/archive/branch.zip --force-reinstall`
