### ISSUE TITLE
Unable to send emails to temporary email addresses

### ISSUE THREAD

**Issue by lyndon-b-johnson** [prtolem/MailTM#14]
# Description:
I encountered an issue while using the pymailtm library to create temporary email addresses and send emails to them. Despite successfully creating a temporary email address using the library, attempts to send emails to this address fail with a DNS error related to the domain fthcapital.com. The error message received is:
```
DNS Error: DNS type 'mx' lookup of fthcapital.com responded with code NXDOMAIN Domain name not found: fthcapital.com
```
![image](https://github.com/prtolem/MailTM/assets/165854527/43afb3d3-973f-4ffa-89df-6e277f17dfaf)

# Steps to Reproduce:
- Install the pymailtm library.
- Use the provided code snippet to create a temporary email address.
- Attempt to send an email to the created temporary email address.

# Code i used:
```python
import asyncio

from pymailtm import MailTm


async def main() -> None:
    mailtm = MailTm()
    temp_mail = mailtm.get_account()
    print(temp_mail.address)
    while True:
        print(temp_mail.get_messages())


if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    loop.run_until_complete(main())
```

# Expected Behavior:
The email should be successfully delivered to the temporary email address created using the pymailtm library.

# Actual Behavior:
The email delivery fails with a DNS error related to the domain fthcapital.com.

# Additional Information:
- Python version: conda env with python 3.9
- Operating system: Windows 11

**Comment by prtolem** [comment]
Hey. Thanks for submitting. This problem is on the side of mail.tm. I can't do anything about it. I can only wait for a fix from the service owner.
