### ISSUE TITLE
2 validation errors for OneMessage

### ISSUE THREAD

**Issue by KldIA6666** [prtolem/MailTM#16]
This is extremely frustrating lmao.

It seems like the get_message_by_id method is failing to parse the response from the API. The error message indicates that there are two validation errors:
- The verifications field is expected to be a list, but it's receiving a dictionary instead.
- The attachments field is required, but it's missing from the response.

I have even attempted reinstalling, it just won't budge.

**Comment by KldIA6666** [comment]
Here's a solution for y'all:

```
class OneMessage(BaseModel):
    id: str
    accountId: str
    msgid: str
    from_: MessageFromTo = Field(alias="from")
    to: list[MessageFromTo]
    cc: list[str]
    bcc: list[str]
    subject: str
    flagged: bool
    isDeleted: bool
    verifications: dict # Changed from list to dict
    retention: bool
    retentionDate: str
    text: str
    html: list[str]
    hasAttachments: bool
    attachments: any = None  # Changed to Any
    size: int
    downloadUrl: str
    createdAt: str
    updatedAt: str
```

**Comment by prtolem** [comment]
hi. download the new version from the repository. This issue has been fixed recently.
