### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by prljav** [prtolem/MailTM#4]
ImportError: cannot import name 'MailTM' from 'mailtm' (C:\Users\marin\AppData\Local\Programs\Python\Python311\Lib\site-packages\mailtm\__init__.py)

**Comment by prtolem** [comment]
Hi. Thank you for choosing to use my library. 
Try installing the library from pypi using 
```
pip install MailTMAPI
```

**Comment by prtolem** [comment]
close issue if the problem is solved
