### ISSUE TITLE
MailTM error & Fix potentially

### ISSUE THREAD

**Issue by RedstonedLife** [prtolem/MailTM#6]
An error I encountered 
```File "C:\Users\Tal A. Baskin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mailtm\__init__.py", line 1, in <module>
    from .mailtm import MailTM
  File "C:\Users\Tal A. Baskin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mailtm\mailtm.py", line 6, in <module>
    from .schemas.domains import Domains, Domain
  File "C:\Users\Tal A. Baskin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mailtm\schemas\domains.py", line 14, in <module>
    class Domains(BaseModel):
  File "C:\Users\Tal A. Baskin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mailtm\schemas\domains.py", line 16, in Domains
    hydra_member: list[Domain] = Field(alias="hydra:member")
TypeError: 'type' object is not subscriptable
```

From my limited research as I don't really have enough time to do all of it, this problem can be fixed by simply changing the imports in `domains.py` and `message.py` from
```py
from pydantic import BaseModel, Field
```
to 
```py
from pydantic import BaseModel as PydanticBaseModel
from pydantic import Field
from pydantic.dataclasses import dataclass

class BaseModel(PydanticBaseModel):
    class Config:
        arbitrary_types_allowed = True
```
        
Above at the top of every file where arbitrary types are used, and as a suggestion to make this run on more Python version I'd avoid using stuff like `list[str]`, It takes maybe 1 more line or 2 to validate if an element, my solution did seem to fix it for me as I am using Python 3.8.7 for this project.

In `domains.py` I changed `hydra_member: list[Domain]` to `hydra_member: list`
And in `message.py` every arbitrary value like `list[someObject]` I changed to `list`
To fix this issue.

I have no confirmed the integrity of the code as in, will it run or not. But I will try, If I encounter more errors I will document them here, If at all possible.

Cheers!

**Comment by prtolem** [comment]
hi. thank you for noticing the bug and trying to fix it! Please specify the code that you used to cause the error
